defaults:
  - hydra/job_logging: custom
  - hydra/output: custom
  - model: qgm_transformer
  - dataset: spider
  - train: default

# Default model settings
seed: 100
glove_embed_path: ./data/glove.42B.300d.txt
log_path: ./logs
hidden_size: 300
dropout: 0.3
clip_grad: 5

# Default training setup
lr: 1e-3
is_bert: false
batch_size: 32
lr_scheduler: true
lr_scheduler_gamma: 5e-1
milestones: [40, 70]
optimizer: Adam
query_type: simple
max_epoch: 100
eval_freq: 1

#
cuda: 0 # -1 to disable
load_model: false
toy: false
debugging: false
tag: tag

