defaults:
  - hydra/job_logging: custom
  - hydra/output: custom
  - encoder: ra_transformer
  - decoder: transformer
  - dataset: spider
  - train: default

# Default model settings
seed: 100
glove_embed_path: ./data/glove.42B.300d.txt
log_path: ./logs
hidden_size: 300
dropout: 0.3
clip_grad: 5

# Default training setup
lr: 1e-3
batch_size: 16
lr_scheduler: true
lr_scheduler_gamma: 1e-1
milestones: [2000, 3000]
optimizer: radam
query_type: simple
max_step_cnt: 4000
#max_epoch: 100
eval_freq: 2
optimize_freq: 8

# bert
bert: 0
is_bert: false
train_bert: true
use_bert_cache: true
reduce_dim: true

# etc
use_down_schema: false
rule: "noqgm" # or semql
remove_punctuation_marks: false
train_glove: false

#
cuda: 0 # -1 to disable
load_model: false
toy: false
debugging: false
tag: tag
